version: "3.8"

services:
  db:
    image: postgres:15.10
    container_name: recruitment_db
    environment:
      POSTGRES_DB: recruitment
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./back-end
    container_name: recruitment_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: recruitment
      DB_PORT: 5432
      NODE_ENV: development
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  frontend:
    build: ./front-end
    container_name: recruitment_frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000
      NODE_ENV: development
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front-end
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
